### ISSUE TITLE
Set up Infinite Zero Server: DigitalOcean

### ISSUE THREAD

**Issue by afkvido** [ProdigyPNP/Zero-Server#2]

**Comment by afkvido** [comment]
It works on http://137.184.246.183

**Comment by afkvido** [comment]
Still gotta do a domain

**Comment by afkvido** [comment]
Imma sleep now. I have a domain in mind, this will be tommorow.

**Comment by donaldli2020** [comment]
https://p-np.prodigypnp.repl.co

**Comment by donaldli2020** [comment]
is 1337.184.246.183 your ip
