### ISSUE TITLE
FIX THE SERVER!!!

### ISSUE THREAD

**Issue by donaldli2020** [ProdigyPNP/Zero-Server#5]

**Comment by donaldli2020** [comment]
![Image](https://user-images.githubusercontent.com/74021676/170118408-67f7b3a4-b129-44b3-9ac3-93a5f0cfb1a8.png)

**Comment by afkvido** [comment]
@donaldli2020 http://infinitezero.net

**Comment by donaldli2020** [comment]
finally wtf

**Comment by afkvido** [comment]
HTTP is the issue, see https://github.com/orgs/ProdigyPNP/projects/1/views/2

**Comment by afkvido** [comment]
*HTTPS

**Comment by donaldli2020** [comment]
![image](https://user-images.githubusercontent.com/74021676/170120416-1eb972d2-1a78-45a2-b64e-cae3ed710862.png)

**Comment by afkvido** [comment]
ima do that rn

**Comment by donaldli2020** [comment]
not secure
